### ISSUE TITLE
Reducing code duplication

### ISSUE THREAD

**Issue by Enoumy** [magsss17/small-cap-stocks#17]
Heyo! I'm one of the TA's whose name starts with "J" and I am reatroactively leaving comments.

I think you could reduce the code duplication here with a higher order function, something like:

```ocaml
let handle_filter ~name ~filter_f = 
      Core.print_endline name;
      return
        (Yojson.Safe.to_string
           ([%to_yojson: Stock.Stock.t list]
              (f portfolio)))
in
```

and then in each branch doing something like:

```ocaml
| "/stock-filter-name" ->
    handler_filter
       ~name:"stock-filter-name"
       ~filter_f:Portfolio.Portfolio.sort_by_name
```

https://github.com/magsss17/small-cap-stocks/blob/e797f0a9be446e337854ab711733b0d0dc79ca53/backend/src/server.ml#L45

**Comment by johnnyr26** [comment]
We ended up removing most of the endpoints and just sticking with two different endpoints. We found that the sorting was more efficient to do in the frontend and therefore didn't need a sorter for the backend.
